version: '3.8'

services:
  django_server:
    build: .
    working_dir: /usr/src/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py generate_test_data 1000 &&
            gunicorn src.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - postgresql_db
      - elasticsearch7
    container_name: django_server

  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - 9200:9200
      - 9300:9300
    container_name: elasticsearch7
    restart: always

  postgresql_db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    env_file: .env
    container_name: postgresql_db

